CREATE TABLE AIRPLANE_CRASHES
(AC_ID INT PRIMARY KEY,
 AC_DATE DATE NOT NULL,
 TIME VARCHAR(150),
 LOCATION VARCHAR(500),
 OPERATOR VARCHAR(500),
 TYPE VARCHAR(500),
 ABOARD INT,
 FATALITIES INT,
 GROUND INT,
 SUMMARY VARCHAR(2500),
 YEAR INT
 );
 
 
 CREATE TABLE WORST_GEO_REGIONS
 (GEO_ID INT PRIMARY KEY,
  COUNTRY VARCHAR(250) NOT NULL,
  ACCIDENTS INT NOT NULL,
  FATALITIES INT NOT NULL,
  GROUND_FATALITIES INT NOT NULL
 );


CREATE TABLE AIRLINES_SAFETY
(AS_ID INT PRIMARY KEY,
 AIRLINES VARCHAR(250),
 INCIDENTS_85_99 INT,
 FATAL_ACCIDENTS_85_99 INT,
 FATALITIES_85_99 INT,
 INCIDENTS_00_14 INT,
 FATAL_ACCIDENTS_00_14 INT,
 FATALITIES_00_14 INT
);

CREATE TABLE WORST_ACCIDENTS
(ACC_ID INT PRIMARY KEY,
 FATALITIES INT NOT NULL,
 ACC_DATE DATE NOT NULL,
 LOCATION VARCHAR(500),
 CARRIER VARCHAR(500),
 TYPE VARCHAR(500)
);